### ISSUE TITLE
https://cuojue.org 评论异常？

### ISSUE THREAD

**Issue by M69W** [weicno/typecho-cache#4]
https://cuojue.org/read/Typecho_Google_Authenticator_02.html
无法提交评论

```
TypeError: Cannot read properties of undefined (reading 'initFancyBox')
    at Object.onCommentLoaded (typecho_plugin_ga.html:3:9293)
    at a.onCommentLoaded (twikoo.all.min.js:2:245294)
    at Array.<anonymous> (twikoo.all.min.js:2:269953)
    at tt (twikoo.all.min.js:2:269352)
```

其实想说感谢一下。
之前用 [GAuthenticator](https://github.com/naicfeng/typecho-Authenticator)

再次，
感谢，
祝一切顺利

**Comment by naicfeng** [comment]
评论系统用的 [Twikoo](https://twikoo.js.org) ，前端js也是用的官方地址。出现的问题也无法复现。

很开心插件帮到了你~
